language: java

addons:
  apt:
    packages:
    - xml2

sudo: required

jdk:
  - oraclejdk8
  
services:
  - docker

script:
  - mvn clean package docker:build

branches:
  only:
  - master
  - develop

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - export REPO=parking-api
  - export VERSION=`xml2 < pom.xml  | grep /project/version= | sed 's/.*=//'`
  - test "$TRAVIS_BRANCH" == 'master' && (docker tag $REPO $DOCKER_REPOSITORY/$REPO; docker tag $REPO $DOCKER_REPOSITORY/$REPO:$VERSION; docker push $DOCKER_REPOSITORY/$REPO:latest; docker push $DOCKER_REPOSITORY/$REPO:$VERSION)
  - test "$TRAVIS_BRANCH" == 'develop' && (docker tag $REPO $DOCKER_REPOSITORY/$REPO:snapshot; docker push $DOCKER_REPOSITORY/$REPO:snapshot)

cache:
  directories:
    - $HOME/.m2
